// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: report/report.proto

package report

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	ReportService_GetSummaryReport_FullMethodName = "/report.ReportService/GetSummaryReport"
	ReportService_GetBudgetReport_FullMethodName  = "/report.ReportService/GetBudgetReport"
)

// ReportServiceClient is the client API for ReportService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ReportServiceClient interface {
	GetSummaryReport(ctx context.Context, in *GetSummaryReportRequest, opts ...grpc.CallOption) (*GetSummaryReportResponse, error)
	GetBudgetReport(ctx context.Context, in *GetBudgetReportRequest, opts ...grpc.CallOption) (*GetBudgetReportResponse, error)
}

type reportServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewReportServiceClient(cc grpc.ClientConnInterface) ReportServiceClient {
	return &reportServiceClient{cc}
}

func (c *reportServiceClient) GetSummaryReport(ctx context.Context, in *GetSummaryReportRequest, opts ...grpc.CallOption) (*GetSummaryReportResponse, error) {
	out := new(GetSummaryReportResponse)
	err := c.cc.Invoke(ctx, ReportService_GetSummaryReport_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reportServiceClient) GetBudgetReport(ctx context.Context, in *GetBudgetReportRequest, opts ...grpc.CallOption) (*GetBudgetReportResponse, error) {
	out := new(GetBudgetReportResponse)
	err := c.cc.Invoke(ctx, ReportService_GetBudgetReport_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReportServiceServer is the server API for ReportService service.
// All implementations should embed UnimplementedReportServiceServer
// for forward compatibility
type ReportServiceServer interface {
	GetSummaryReport(context.Context, *GetSummaryReportRequest) (*GetSummaryReportResponse, error)
	GetBudgetReport(context.Context, *GetBudgetReportRequest) (*GetBudgetReportResponse, error)
}

// UnimplementedReportServiceServer should be embedded to have forward compatible implementations.
type UnimplementedReportServiceServer struct {
}

func (UnimplementedReportServiceServer) GetSummaryReport(context.Context, *GetSummaryReportRequest) (*GetSummaryReportResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSummaryReport not implemented")
}
func (UnimplementedReportServiceServer) GetBudgetReport(context.Context, *GetBudgetReportRequest) (*GetBudgetReportResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBudgetReport not implemented")
}

// UnsafeReportServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReportServiceServer will
// result in compilation errors.
type UnsafeReportServiceServer interface {
	mustEmbedUnimplementedReportServiceServer()
}

func RegisterReportServiceServer(s grpc.ServiceRegistrar, srv ReportServiceServer) {
	s.RegisterService(&ReportService_ServiceDesc, srv)
}

func _ReportService_GetSummaryReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSummaryReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReportServiceServer).GetSummaryReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReportService_GetSummaryReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReportServiceServer).GetSummaryReport(ctx, req.(*GetSummaryReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReportService_GetBudgetReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBudgetReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReportServiceServer).GetBudgetReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReportService_GetBudgetReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReportServiceServer).GetBudgetReport(ctx, req.(*GetBudgetReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ReportService_ServiceDesc is the grpc.ServiceDesc for ReportService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ReportService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "report.ReportService",
	HandlerType: (*ReportServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSummaryReport",
			Handler:    _ReportService_GetSummaryReport_Handler,
		},
		{
			MethodName: "GetBudgetReport",
			Handler:    _ReportService_GetBudgetReport_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "report/report.proto",
}
